services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: newsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/000001_create_initial_tables.up.sql:/docker-entrypoint-initdb.d/000001_create_initial_tables.up.sql:ro
    ports:
      - "5432:5432"

  aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://admin:admin@postgres:5432/newsdb?sslmode=disable"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
