version: "3.8"

services:
  aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@host.docker.internal:5432/newsdb
    ports:
      - "8080:8080"
